### ISSUE TITLE
CLI tool should return a non-zero code when there's a diff

### ISSUE THREAD

**Issue by dasevilla** [zallek/swagger-diff#19]
It would be nice for script writing to be able to check the return code of the CLI tool. If a value other than zero is returned, there was a diff.

**Comment by zallek** [comment]
Actually it's already the case https://github.com/zallek/swagger-diff/blob/master/bin/swagger-diff.js#L79
if there is some diff considered as "errors", https://github.com/zallek/swagger-diff#levels-of-log, it returns 1. otherwise 0

**Comment by dasevilla** [comment]
Thanks!
